name: Reminder Notif Scheduler

on:
  schedule:
    - cron: '0 0 * * *' # Setiap hari jam 07:00 WIB (00:00 UTC)
  workflow_dispatch:

jobs:
  reminder-notif:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run reminder notification
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: python reminder_notif.py
